project_id = "mqcblaumtbroeuckvnzn"

[functions.generate-summary]
verify_jwt = false

[functions.parse-document]
verify_jwt = false

[functions.google-calendar-auth]
verify_jwt = false

[functions.google-calendar-sync]
verify_jwt = false

[functions.generate-flashcards]
verify_jwt = false

[functions.generate-diagram]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.generate-quiz]
verify_jwt = false

[functions.start-voice-quiz]
verify_jwt = false
