/**
 * Quiz Service
 * Replace with real API when AI endpoint is available.
 */

import type { Quiz } from "@/types/quiz";

/**
 * Generate a quiz from content/topic.
 * TODO: Replace with real AI API call.
 */
export async function generateQuiz(content: string): Promise<Quiz> {
  // Simulate network delay
  await new Promise((resolve) => setTimeout(resolve, 2000));

  // Temporary mock — clearly marked for replacement
  const id = crypto.randomUUID();
  return {
    id,
    topic: content.slice(0, 50),
    createdAt: new Date().toISOString(),
    questions: [
      {
        id: crypto.randomUUID(),
        question: `Based on the provided content about "${content.slice(0, 30)}...", which statement is most accurate?`,
        options: [
          "This is a placeholder option A",
          "This is a placeholder option B",
          "This is a placeholder option C",
          "This is a placeholder option D",
        ],
        correctAnswer: 0,
        explanation: "This is a mock question. Real questions will be generated by AI.",
      },
      {
        id: crypto.randomUUID(),
        question: "What is the key concept discussed in the material?",
        options: [
          "Concept Alpha",
          "Concept Beta",
          "Concept Gamma",
          "Concept Delta",
        ],
        correctAnswer: 1,
        explanation: "Mock explanation — will be replaced by AI-generated content.",
      },
      {
        id: crypto.randomUUID(),
        question: "Which of the following best describes the main idea?",
        options: [
          "Summary statement A",
          "Summary statement B",
          "Summary statement C",
          "Summary statement D",
        ],
        correctAnswer: 2,
      },
    ],
  };
}
