// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqcblaumtbroeuckvnzn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xY2JsYXVtdGJyb2V1Y2t2bnpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwMDkzNDAsImV4cCI6MjA4NTU4NTM0MH0.af4gEZv-Y-9GXAMjLv8QaUv_QJaLbo9SpWIHD02wpYk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});